[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyDU9a8RwVUMTggsJozOgO2lKA2I15PEPuI"
  VITE_FIREBASE_AUTH_DOMAIN = "deep-finance-355f1.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "deep-finance-355f1"
  VITE_FIREBASE_STORAGE_BUCKET = "deep-finance-355f1.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "805021126677"
  VITE_FIREBASE_APP_ID = "1:805021126677:web:54bf662b2f00ae89a13e1c"